### ISSUE TITLE
Why not parse ffprobe output as JSON ?

### ISSUE THREAD

**Issue by auguster** [rodrigopolo/plotframes#2]
Hello,

On a project I had to analyse a video to figure out why the playback is messed up. I noticed your project and on reviewing your code I was surprise to see that you manually parsed the output of ffprobe using regex.

I think you should use add `"-print_format", "json"` to your ffprobe spawn and parse the result using JSON.parse. It would parse all the fields for you. I think this would reduce your code base and increase the maintainability of your project.

Best regards.

**Comment by rodrigopolo** [comment]
Indeed, using JSON was an option, but dealing with JSON.parse is not as simple as it seems, considering the child process streams its STDOUT to the main process, some extra libs for parsing portions of JSON streams is needed, also, using JSON increase the STDOUT output to almost 200%, and in some cases the STDOUT isn’t JSON, that is why I decided to parse it from plain text using Regex.

I’ll try with JSON in my spare time just to see how it performs, out of curiosity.

Thanks for the observation, I really appreciate it. 

RodrigoPolo.com

**Comment by auguster** [comment]
I just did that to analyze the sequence of frames in a (short) video stream. What I did is concat the output of stdout in a string buffer and when it reaches the end, without error, I parse the JSON. It worked well for a few minutes of video but I'm not sure how it behaves for long video, maybe the buffer becomes to big. You're right, it might not be the best approach.

**Comment by rodrigopolo** [comment]
Indeed, dealing with unknown lengths of video, encoders and frames makes difficult to guestimate the necesary buffer size, so a pipe from one child proccess to another is better. Offtopic, nice CV, and an interesting company, from the same country that give us Fabrice Bellard, my respect to you.
